configuration:
  amfName: AMF
  ngapIpList:
    - 10.100.200.11          # <- IP de N2 en sbi_net, no 0.0.0.0
  ngapPort: 38412
  sbi:
    scheme: http
    registerIPv4: amf        # nombre DNS resoluble por Docker
    bindingIPv4: 0.0.0.0
    port: 8000
  nrfUri: http://nrf:8000

  servedGuamiList:
    - plmnId:
        mcc: '732'
        mnc: '101'
      amfId: cafe00          # 6 dígitos hex: RegionId(2)+SetId(3)+Pointer(1)

  supportTaiList:
    - plmnId:
        mcc: '732'
        mnc: '101'
      tac: '000001'          # == tac: 1 en gnb.yaml

  plmnSupportList:
    - plmnId:
        mcc: '732'
        mnc: '101'
      snssaiList:
        - sst: 1
          sd: '010203'

  supportDnnList:
    - internet

  security:
    integrityOrder:  [ NIA2 ]
    cipheringOrder:  [ NEA0 ]   # NEA0 = sin cifrado, facilita el análisis con tcpdump

  networkName:
    full: lab5g-co
    short: lab5g