version: 1.0.3
description: UPF configuration - lab5g

pfcp:
  addr: 10.100.200.20
  nodeID: 10.100.200.20
  retransTimeout: 1s
  maxRetrans: 3

gtpu:
  forwarder: gtp5g
  ifList:
    - addr: 10.100.201.20        # n3_net
      type: N3

dnnList:
  - dnn: internet
    cidr: 10.60.0.0/16
    natifname: dn0               # nombre lógico; ver script de iptables

logger:
  enable: true
  level: debug
  reportCaller: false